---
driver:
  name: vagrant
  customize: 
    memory: 2048

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[chef-lamp-jenkins::default]
